---
signal:
    sr: 16000
    win_length: 400
    hop_length: 80
    n_fft: 512
    n_mels: 40
    max_db: 35
    min_db: -55
    length: 16000
model: 'DefaultModel'
train:
    tar_path: '/path/to/tar/train/*.wav'
    ntar_path: '/path/to/ntar/train/*.wav'
    tar_labels: (0., 1.)
    ntar_labels: (1., 0.)
    batch_size: 8
    num_gpu: 1
    lr: 0.0002
    num_epochs: 100000
    steps_per_epoch: 100
    tar_ratio: 0.5
eval:
    tar_path: '/path/to/tar/eval/*.wav'
    ntar_path: '/path/to/ntar/eval/*.wav'
    batch_size: 32
disc:
    data_path: 'path/to/data/*.wav'
    tar_path: '/path/to/tar/disc/*.wav'
    ntar_path: '/path/to/ntar/disc/*.wav'
    batch_size: 8
    threshold: 0.9
logdir_path: '/path/to/logdir'