---
signal:
    sr: 16000
    win_length: 400
    hop_length: 80
    n_fft: 512
    n_mels: 80
    max_db: 35
    min_db: -55
    length: 4000
train:
    tar_path: '/data/public/rw/IU/*_split/*.wav'
    ntar_path: '/data/public/rw/arctic/*/*.wav'
    batch_size: 256
    num_gpu: 4
    lr: 0.0002
    num_epochs: 100000
    steps_per_epoch: 100
    save_per_epoch: 100
eval:
    data_path: '/data/public/rw/IU/*_split/*.wav'
    batch_size: 3
logdir_path: '/data/private/voice-discriminator/logdir'